In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import scipy.linalg
%matplotlib inline

#1. Решите линейную систему:

In [4]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
X = np.linalg.solve(A,B)
X

array([-9.2       ,  0.9       ,  6.46666667])

#2. Найдите псевдорешение:

In [6]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2], [2,0,-5], [11,4,-7]])
B = np.array([1,7,12,7,15])
X = np.linalg.lstsq(A,B)
X

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#3. Сколько решений имеет линейная система:

In [55]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([12,2,1])
#В изначальном виде линейна система не имееет решений
#Можно проверить так (по теореме Кронекера - Капелли):
print(np.linalg.matrix_rank(np.concatenate((A, B.reshape((-1,1))), axis=1)), np.linalg.matrix_rank(A))

#В качестве примера возмем:
B = np.array([14,32,50])
print(np.linalg.matrix_rank(np.concatenate((A, B.reshape((-1,1))), axis=1)), np.linalg.matrix_rank(A))
#Линейная система будет иметь бесконечное кол-во решений (т.к. ранги обычной и расширенной матрицы равны и меньше числа неизвестных)
# при любом B в котором 2*b2 - b1 - b3 = 0

#В общем виде все решения можно будет записать как ситему уравнений которая решается для любого z для любого набора B в котором 2*b2 - b1 - b3 = 0:

# 2*b2 - b1 - b3 = 0
# x = z - 1/3 * (5*b1 - 2*b2)
# y = 1/3 *(4*b1 - b2) - 2z



3 2
2 2


#4. Вычислите LU-разложение матрицы:

In [65]:
A = np.array([[1,2,3],[2,16,21],[4,28,73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)
#B = np.dot (A, np.array([1,2,3]))
B = np.array([3,64,12])

np.linalg.solve(A, B)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


array([-5.32407407,  8.18981481, -2.68518519])

#5. Найдите нормальное псевдорешение недоопределенной системы:

In [69]:
A = np.array([[1,2,-1], [8, -5, 2]])
B = np.array([1,2])
np.linalg.lstsq(A,B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 0.42250923,  0.22509225, -0.12730627]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

#6. Найдите одно из псевдорешений вырожденной системы:

In [70]:
A = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
np.linalg.lstsq(A,B)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))