In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#1. Решите линейную систему:

In [4]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
X = np.linalg.solve(A,B)
X

array([-9.2       ,  0.9       ,  6.46666667])

#2. Найдите псевдорешение:

In [6]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2], [2,0,-5], [11,4,-7]])
B = np.array([1,7,12,7,15])
X = np.linalg.lstsq(A,B)
X

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

#3. Сколько решений имеет линейная система:

In [20]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([12,2,1])
#В изначальном виде линейна система не имееет решений
#Линейная система будет иметь бесконечное кол-во решений при любом B в котором 2*b2 - b1 - b3 = 0
#В качестве примера возмем B = [14,32,50]
#В общем виде все решения можно будет записать как ситему уравнений которая решается для любого z для любого набора B в котором 2*b2 - b1 - b3 = 0:

# 2*b2 - b1 - b3 = 0
# x = z - 1/3 * (5*b1 - 2*b2)
# y = 1/3 *(4*b1 - b2) - 2z

In [17]:
B = np.dot(A, np.array([1,2,3]))
print(B)  
#np.array([12,2,1])
#X = np.linalg.solve(A,B)
#X

[14 32 50]


#4. Вычислите LU-разложение матрицы:

In [18]:
- 14 * 17 - 50*3 + 32*6 

-196

#5. Найдите нормальное псевдорешение недоопределенной системы:

#6. Найдите одно из псевдорешений вырожденной системы: